"use client";

import { useParams } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ChevronDown, ExternalLink, Sparkles, ThumbsDown, ThumbsUp, Workflow } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { ScoreBadge } from "@/components/shared/score-badge";
import { ScoreBar } from "@/components/shared/score-bar";
import { PageHeader } from "@/components/shared/page-header";
import {
  findOpportunity,
  mockOpportunities,
  mockSignals,
  mockProducts,
  mockUsers,
} from "@/mock/data";
import { formatUsd, timeAgo } from "@/lib/utils/format";

export default function OpportunityDetailPage() {
  const { id } = useParams<{ id: string }>();
  const opp = findOpportunity(id);
  if (!opp) return <div className="p-6 text-sm text-slate-400">Opportunity not found.</div>;

  const sourceProducts = opp.sourceProductIds.map((pid) => mockProducts.find((p) => p.id === pid)).filter(Boolean);
  const sourceSignals = opp.sourceSignalIds.map((sid) => mockSignals.find((s) => s.id === sid)).filter(Boolean);
  const similar = mockOpportunities
    .filter((o) => o.id !== opp.id && o.niche === opp.niche)
    .slice(0, 4);

  return (
    <>
      <Button variant="ghost" size="sm" className="mb-3" asChild>
        <Link href="/opportunities">
          <ArrowLeft className="mr-1 h-4 w-4" /> Back to opportunities
        </Link>
      </Button>

      <PageHeader
        title={opp.title}
        description={opp.summary}
        actions={
          <>
            <Button variant="outline" size="sm">
              <ThumbsUp className="mr-1 h-4 w-4" /> {opp.votes.up}
            </Button>
            <Button variant="outline" size="sm">
              <ThumbsDown className="mr-1 h-4 w-4" /> {opp.votes.down}
            </Button>
            <Button size="sm" asChild>
              <Link href={`/brain?mode=opportunity&id=${opp.id}`}>
                <Sparkles className="mr-1 h-4 w-4" /> Ask Brain
              </Link>
            </Button>
          </>
        }
      />

      <div className="mb-4 flex flex-wrap gap-2">
        <ScoreBadge score={opp.score} size="lg" />
        <Badge variant="outline">{opp.niche.replace(/_/g, " ")}</Badge>
        <Badge variant="outline">{opp.opportunityType.replace(/_/g, " ")}</Badge>
        <Badge variant="outline">
          <Workflow className="mr-1 h-3 w-3" /> {opp.buildEffort.replace(/_/g, " ")}
        </Badge>
        <Badge variant="info">{opp.status}</Badge>
        <Badge variant="success" className="font-mono">
          proj. {formatUsd(opp.projectedRevenueUsd, { compact: true })}
        </Badge>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        <div className="space-y-6 lg:col-span-2">
          <Card className="border-slate-800 bg-slate-900/40">
            <CardHeader>
              <CardTitle>AI rationale</CardTitle>
              <CardDescription>Why this opportunity surfaced.</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm leading-relaxed text-slate-300">{opp.aiRationale}</p>
            </CardContent>
          </Card>

          <Card className="border-slate-800 bg-slate-900/40">
            <CardHeader>
              <CardTitle>Build plan</CardTitle>
              <CardDescription>Generated by Claude · {opp.buildEffort.replace(/_/g, " ")} cadence.</CardDescription>
            </CardHeader>
            <CardContent>
              <Collapsible defaultOpen>
                <CollapsibleTrigger asChild>
                  <Button variant="ghost" size="sm" className="mb-2 gap-1">
                    Phases <ChevronDown className="h-3 w-3" />
                  </Button>
                </CollapsibleTrigger>
                <CollapsibleContent className="space-y-3">
                  {opp.aiBuildPlan.weeks.map((w) => (
                    <div key={w.label} className="rounded-md border border-slate-800 bg-slate-950/40 p-3">
                      <div className="text-xs font-semibold uppercase tracking-wide text-slate-300">{w.label}</div>
                      <ul className="mt-2 space-y-1 text-sm text-slate-300">
                        {w.deliverables.map((d) => (
                          <li key={d} className="flex items-start gap-2">
                            <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
                            {d}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </CollapsibleContent>
              </Collapsible>

              <div className="mt-4 grid gap-3 md:grid-cols-2">
                <div>
                  <div className="text-xs font-semibold uppercase text-slate-400">Stack</div>
                  <ul className="mt-1 flex flex-wrap gap-1">
                    {opp.aiBuildPlan.stack.map((s) => (
                      <Badge key={s} variant="outline" className="text-[10px]">
                        {s}
                      </Badge>
                    ))}
                  </ul>
                </div>
                <div>
                  <div className="text-xs font-semibold uppercase text-slate-400">Monetization</div>
                  <ul className="mt-1 list-inside list-disc text-xs text-slate-300">
                    {opp.aiBuildPlan.monetization.map((m) => (
                      <li key={m}>{m}</li>
                    ))}
                  </ul>
                </div>
                <div>
                  <div className="text-xs font-semibold uppercase text-slate-400">Risks</div>
                  <ul className="mt-1 list-inside list-disc text-xs text-slate-300">
                    {opp.aiBuildPlan.risks.map((r) => (
                      <li key={r}>{r}</li>
                    ))}
                  </ul>
                </div>
                <div>
                  <div className="text-xs font-semibold uppercase text-slate-400">Success metrics</div>
                  <ul className="mt-1 list-inside list-disc text-xs text-slate-300">
                    {opp.aiBuildPlan.successMetrics.map((m) => (
                      <li key={m}>{m}</li>
                    ))}
                  </ul>
                </div>
              </div>
            </CardContent>
          </Card>

          <Tabs defaultValue="signals">
            <TabsList>
              <TabsTrigger value="signals">Source signals</TabsTrigger>
              <TabsTrigger value="products">Source products</TabsTrigger>
              <TabsTrigger value="similar">Similar opps</TabsTrigger>
              <TabsTrigger value="annotations">Annotations</TabsTrigger>
            </TabsList>
            <TabsContent value="signals">
              <Card className="border-slate-800 bg-slate-900/40">
                <CardContent className="space-y-2 p-3">
                  {sourceSignals.map((s) => (
                    <div key={s!.id} className="rounded-md border border-slate-800 bg-slate-950/40 p-3 text-sm">
                      <div className="flex items-center justify-between">
                        <Badge variant="outline" className="text-[10px] uppercase">
                          {s!.signalType.replace(/_/g, " ")}
                        </Badge>
                        <span className="text-xs text-slate-500">{timeAgo(s!.processedAt)}</span>
                      </div>
                      <div className="mt-1 line-clamp-1 font-medium">{s!.title}</div>
                      <div className="mt-0.5 text-xs text-slate-500">{s!.snippet}</div>
                      <a
                        href={s!.sourceUrl}
                        className="mt-1 inline-flex items-center gap-1 text-xs text-sky-400 hover:underline"
                      >
                        Source <ExternalLink className="h-3 w-3" />
                      </a>
                    </div>
                  ))}
                </CardContent>
              </Card>
            </TabsContent>
            <TabsContent value="products">
              <Card className="border-slate-800 bg-slate-900/40">
                <CardContent className="space-y-2 p-3">
                  {sourceProducts.map((p) => (
                    <Link
                      key={p!.id}
                      href={`/products/${p!.id}`}
                      className="block rounded-md border border-slate-800 bg-slate-950/40 p-3 hover:bg-slate-900"
                    >
                      <div className="flex items-center justify-between">
                        <div className="text-sm font-medium">{p!.title}</div>
                        <span className="text-xs font-semibold text-emerald-400">{formatUsd(p!.priceUsd ?? 0)}</span>
                      </div>
                      <div className="mt-0.5 text-xs text-slate-500">
                        {p!.creator} · {p!.sourcePlatform.replace(/_/g, " ")}
                      </div>
                    </Link>
                  ))}
                </CardContent>
              </Card>
            </TabsContent>
            <TabsContent value="similar">
              <Card className="border-slate-800 bg-slate-900/40">
                <CardContent className="grid gap-2 p-3 md:grid-cols-2">
                  {similar.map((o) => (
                    <Link key={o.id} href={`/opportunities/${o.id}`} className="rounded-md border border-slate-800 bg-slate-950/40 p-3 hover:bg-slate-900">
                      <div className="flex items-center gap-2">
                        <ScoreBadge score={o.score} size="sm" />
                        <span className="line-clamp-1 text-sm font-medium">{o.title}</span>
                      </div>
                      <div className="mt-1 line-clamp-2 text-xs text-slate-500">{o.summary}</div>
                    </Link>
                  ))}
                </CardContent>
              </Card>
            </TabsContent>
            <TabsContent value="annotations">
              <Card className="border-slate-800 bg-slate-900/40">
                <CardContent className="space-y-2 p-3">
                  <div className="rounded-md border border-slate-800 bg-slate-950/40 p-3 text-xs">
                    <div className="flex items-center justify-between">
                      <span className="font-medium text-slate-200">{mockUsers[0]!.name}</span>
                      <span className="text-slate-500">{timeAgo(opp.updatedAt)}</span>
                    </div>
                    <div className="mt-1 text-slate-300">
                      Want to validate via TikTok demo first. Add a 60-second screen recording link before committing.
                    </div>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>
        </div>

        <div className="space-y-6">
          <Card className="border-slate-800 bg-slate-900/40">
            <CardHeader>
              <CardTitle>Score breakdown</CardTitle>
              <CardDescription>5-dimension heuristic + rules.</CardDescription>
            </CardHeader>
            <CardContent>
              <ScoreBar breakdown={opp.scoreBreakdown} />
            </CardContent>
          </Card>

          <Card className="border-slate-800 bg-slate-900/40">
            <CardHeader>
              <CardTitle className="text-base">Quick stats</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2 text-xs">
              <Row label="Created" value={timeAgo(opp.createdAt)} />
              <Row label="Updated" value={timeAgo(opp.updatedAt)} />
              <Row label="By" value={opp.createdBy === "ai" ? "AI Tier 3" : "User"} />
              <Row label="Niche" value={opp.niche.replace(/_/g, " ")} />
              <Row label="Status" value={opp.status} />
              <Row label="Saved" value={opp.saved ? "Yes" : "No"} />
            </CardContent>
          </Card>
        </div>
      </div>
    </>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between">
      <span className="text-slate-500">{label}</span>
      <span className="text-slate-300">{value}</span>
    </div>
  );
}
